classic: false # override options for ls backwards compatibility

# Columns
blocks:
  - permission
  - user
  - group
  - size
  - date
  - name
  # - context
  # - inode
  # - links
  # - git

# display block headers.
header: false

color:
  when: auto # never, auto, always
  theme: default # default, custom ~ will look in the config directory for `colors.yaml`

date: date # date, relative, '+<date_format>' ~ `strftime` formatted value

# dereference symbolic links
dereference: false

icons:
  when: never # always, auto, never
  theme: unicode # fancy, unicode
  # Separator between icon and the name
  separator: " "

ignore-globs:
  - .git

# add indicator characters to certain listed files
indicators: false

layout: grid # grid, tree, oneline

recursion:
  enabled: false
  # depth: 3

size: default # default, short, bytes

# display the total size of directories.
total-size: false

permission: rwx # rwx, octal

sorting:
  column: name # extension, name, time, size, version
  reverse: false
  dir-grouping: none # first, last, none

# omit showing symlink targets
no-symlink: false

# attach hyperlink to filenames
hyperlink: never # always, auto, never

symlink-arrow: ⇒

