# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# vim:fileencoding=utf-8:foldmethod=marker


[flavor]
use = ""


[manager]
cwd = { fg = "#999999" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = false }

# Find
find_keyword  = { fg = "black", bg = "#ffafff", bold = true }
find_position = { bg = "reset", italic = true }

# Marker
marker_copied   = { fg = "green",       bg = "black" }
marker_cut      = { fg = "red",         bg = "black" }
marker_marked   = { fg = "#ffafff",     bg = "black" }
marker_selected = { fg = "#ffafff",     bg = "black" }

# Tab
tab_active   = { fg = "#dadada", bg = "#202020" } # whiteish
tab_inactive = { fg = "#888888" }
tab_width    = 1

# Count
count_copied   = { fg = "white", bg = "green" }
count_cut      = { fg = "white", bg = "red" }
count_selected = { fg = "#ffafff", bg = "black" }

# Border
border_symbol = "▎"
border_style  = { fg = "#444444", bold = true } # border gray

# Highlighting
syntect_theme = ""


[status]
separator_open  = "█"
separator_close = "█"
separator_style = { fg = "gray", bg = "gray" }

# Mode
mode_normal = { bg = "#36a3d9", fg = 'black', bold = false } # blue
mode_select = { bg = "#ff5f5f", bold = false } # red
mode_unset  = { bg = "#ff5f5f", bold = false } # red

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#36a3d9", bg = "black" } # blue
progress_error  = { fg = "red", bg = "black" }

# Permissions
permissions_t = { fg = "green" }
permissions_r = { fg = "yellow" }
permissions_w = { fg = "red" }
permissions_x = { fg = "cyan" }
permissions_s = { fg = "darkgray" }


[select]
border   = { fg = "blue" }
active   = { fg = "magenta", bold = true }
inactive = {}


[input]
border   = { fg = "#444444" } # border gray
title    = { bold = true }
value    = {fg = "#dadada"}
selected = { reversed = true }


[completion]
border   = { fg = "#444444" } # border gray
active   = { reversed = true }
inactive = {}


[tasks]
border   = { fg = "#444444" } # border gray
title   = {}
hovered = { fg = "lightmagenta" }


[which]
cols            = 3
mask            = { bg = "black" }
cand            = { fg = "#99df87", bg = "#202020"  } # green
rest            = { }
desc            = { fg =  "#aaaaaa", bg = "#202020"  } # like the status bar : help in vim
separator       = " "
separator_style = { bg = "#202020" }


[help]
on      = { fg = "#99df87" } # green
run     = { fg = "#dadada" } # whiteish
desc    = {}
hovered = { reversed = true, bold = true }
footer  = { fg = "black", bg = "white" }


[notify]
title_info  = { fg = "green" }
title_warn  = { fg = "yellow" }
title_error = { fg = "red" }


[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#aaaaaa" },
	{ mime = "{audio,video}/*", fg = "#aaaaaa" },

	# Archives
	{ mime = "application/*zip", fg = "darkgray" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "darkgray" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "darkgray" },

    # sh scripts
	{ mime = "text/shellscript", fg = "lightcyan"},

	# Fallback
    { name = "*/", fg = "#87ff87" }, # green
	{ name = "*", fg = "#dadada" }, # whiteish
]

[icon]

# reset defaults
globs = []
dirs = []
files = []
exts = []

conds = [
	{ if = "dir",  text = "◼" ,  fg = "#666666"},
	{ if = "!dir", text = "" }
]
