[ manager ]

linemode = "mtime"
show_symlink = true
ratio = [1, 4, 3]



[plugin]

#  git clone https://github.com/mgumz/yazi-plugin-bat.git ~/.config/yazi/plugins/bat.yazi
prepend_previewers = [
	{ mime = "text/*"    , run = "bat" },
]
