-- vim.pack.add {
--     { src = "https://github.com/github/copilot.vim" },
--     { src = "https://github.com/nvim-lua/plenary.nvim", version = "master" },
--     { src = "https://github.com/CopilotC-Nvim/CopilotChat.nvim" },
-- }
--
-- -- Copilot.vim
-- vim.keymap.set(
--     "i",
--     "<C-l>",
--     'copilot#Accept("<CR>")',
--     { expr = true, noremap = true, silent = true, replace_keycodes = false, desc = "copilot autocomplete" }
-- )
-- vim.keymap.set("n", "<leader>l", ":CopilotChatToggle<CR>", { desc = "copilot chat" })
--
-- -- CopilotChat
-- require("CopilotChat").setup {
--     model = "gpt-5",
--     mappings = {
--         reset = {
--             normal = "",
--             insert = "",
--         },
--     },
-- }
